import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from 'next/headers'

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Traveller Gateway",
	description: "Generated by create next app",
};

// export default function RootLayout({
// 	children,
// }: Readonly<{
// 	children: React.ReactNode;
// }>) {
// 	return (
// 		<html lang="en">
// 			<body
// 				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// 			>
// 				{children}
// 			</body>
// 		</html>
// 	);
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const host = headers().get('host') || ''
  const tenant = host.replace(/^www\./, '')

  return (
    <html lang="en">
      <body>
        <header className="p-4 bg-gray-100">Tenant: {tenant}</header>
        {children}
      </body>
    </html>
  )
}
